name: dtm
channels:
  - defaults
  - fastai
  - pytorch
dependencies:
  - ipython=7.26.0
  - keras=2.4.3
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pandas=1.3.2
  - pyserial
  - pytorch
  - pip=21.2.4
  - pip:
      - traci
      - ipykernel
